#!/bin/bash
# 🚀 SEO Deployment Checklist for GbanaMarket

echo "===================================================="
echo "GbanaMarket SEO Optimization - Deployment Checklist"
echo "===================================================="
echo ""

# Step 1: Git Status Check
echo "✓ Step 1: Verify Git Status"
git status --short

echo ""
echo "⚠️  These files should be MODIFIED (M):"
echo "   - app/layout.tsx"
echo "   - app/page.tsx"
echo "   - app/listings/[id]/page.tsx"
echo "   - app/sitemap.ts"
echo "   - app/robots.ts"

echo ""
echo "✓ Step 2: Verify New Files Created"
git status --short | grep "^??" || echo "   No untracked files to verify"

echo ""
echo "===================================================="
echo "Files to be committed (verify manually):"
echo "===================================================="
echo "CREATED:"
echo "  ✓ lib/schema.ts"
echo "  ✓ public/robots.txt"  
echo "  ✓ SEO_IMPLEMENTATION.md"
echo "  ✓ SEO_DEPLOYMENT_CHECKLIST.sh (this file)"
echo ""
echo "MODIFIED:"
echo "  ✓ app/layout.tsx (#1 Priority)"
echo "  ✓ app/page.tsx"
echo "  ✓ app/listings/[id]/page.tsx (#2 Priority)"
echo "  ✓ app/sitemap.ts"
echo "  ✓ app/robots.ts"
echo ""

echo "===================================================="
echo "🚀 DEPLOYMENT STEPS"
echo "===================================================="
echo ""

echo "1. Test locally (optional):"
echo "   $ npm run build"
echo "   $ npm run dev"
echo "   # Open http://localhost:3000"
echo "   # Check console for errors"
echo ""

echo "2. Commit all changes:"
echo "   $ git add ."
echo "   $ git commit -m 'feat: comprehensive SEO optimization'"
echo ""

echo "3. Push to GitHub:"
echo "   $ git push origin main"
echo ""

echo "4. Vercel auto-deploys (wait 2-3 minutes)"
echo ""

echo "5. Verify URLs are live:"
echo "   $ curl https://gbanamarket.vercel.app/sitemap.xml"
echo "   $ curl https://gbanamarket.vercel.app/robots.txt"
echo "   $ curl https://gbanamarket.vercel.app/listings/{any-id}"
echo ""

echo "===================================================="
echo "✅ POST-DEPLOYMENT VERIFICATION"
echo "===================================================="
echo ""

echo "1. ✓ Check Meta Tags:"
echo "   - Open https://gbanamarket.vercel.app"
echo "   - Inspect page source (Ctrl+U)"
echo "   - Look for <meta name=\"og:*\">"
echo "   - Look for <script type=\"application/ld+json\">"
echo ""

echo "2. ✓ Verify Structured Data:"
echo "   - Use https://schema.org/validator/"
echo "   - Paste HTML and verify:"
echo "     * WebSite schema"
echo "     * Organization schema"
echo "   - Visit product page and verify:"
echo "     * Product schema"
echo "     * BreadcrumbList schema"
echo ""

echo "3. ✓ Check Sitemaps:"
echo "   - Visit https://gbanamarket.vercel.app/sitemap.xml"
echo "   - Should show 100+ <url> entries"
echo "   - Check robots.txt at /robots.txt"
echo ""

echo "4. ✓ Test Rich Results:"
echo "   - Use https://search.google.com/test/rich-results"
echo "   - Paste URL: https://gbanamarket.vercel.app"
echo "   - Verify Product rich results recognized"
echo ""

echo "5. ✓ Mobile Friendly Test:"
echo "   - Use https://search.google.com/test/mobile-friendly"
echo "   - Verify no mobile issues"
echo ""

echo "===================================================="
echo "📋 GOOGLE SEARCH CONSOLE STEPS (After Deployment)"
echo "===================================================="
echo ""

echo "1. Go to: https://search.google.com/search-console"
echo ""

echo "2. ✓ Verify Site Ownership"
echo "   - Select domain: gbanamarket.vercel.app"
echo "   - Use HTML file method (already uploaded!)"
echo "   - Click 'Verify'"
echo ""

echo "3. ✓ Submit Sitemap"
echo "   - Sitemaps > New Sitemap"
echo "   - URL: https://gbanamarket.vercel.app/sitemap.xml"
echo "   - Click 'Submit'"
echo "   - Should show 'SUCCESS'"
echo ""

echo "4. ✓ Request Indexing for Key Pages"
echo "   - URL Inspection tool"
echo "   - Test: https://gbanamarket.vercel.app/"
echo "   - Click 'Request Indexing'"
echo "   - Repeat for /sell page"
echo "   - Test 2-3 product pages"
echo ""

echo "5. ✓ Monitor Performance"
echo "   - Settings > Preferred Domain"
echo "   - Set to: https://gbanamarket.vercel.app"
echo "   - Performance tab to track impressions"
echo ""

echo "===================================================="
echo "🎯 NEXT STEPS (Long-term SEO)"
echo "===================================================="
echo ""

echo "✓ Weekly:"
echo "  - Monitor Google Search Console for crawl errors"
echo "  - Check Coverage report for blocked pages"
echo "  - Review performance data"
echo ""

echo "✓ Monthly:"
echo "  - Check rich results in GSC"
echo "  - Review keyword rankings in Analytics"
echo "  - Monitor organic traffic growth"
echo ""

echo "✓ Quarterly:"
echo "  - Add more structured data (ratings, reviews)"
echo "  - Create category hub pages"
echo "  - Build backlinks from local directories"
echo ""

echo "===================================================="
echo "❓ TROUBLESHOOTING"
echo "===================================================="
echo ""

echo "Q: Sitemap shows 404?"
echo "A: Wait 3-5 minutes for Vercel deployment, then refresh"
echo ""

echo "Q: Rich results not showing?"
echo "A: Check schema.org validator, may need 1-2 weeks for indexing"
echo ""

echo "Q: Links not in Google Index?"
echo "A: Submit via Search Console > URL Inspection > Request Indexing"
echo ""

echo "Q: Robots.txt error?"
echo "A: Both app/robots.ts AND public/robots.txt are deployed"
echo ""

echo "===================================================="
echo "✅ ALL READY! Push your code now!"
echo "===================================================="
echo ""
